[build]
    command = "ng build"
    publish = "dist/browser"

    [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
    [[headers]]
    for = "/*"
    [headers.values]
    X-Prerender-Status = "true"