[phases.setup]
nixPkgs = ["nodejs-18_x", "nodejs", "npm"]

[phases.install]
cmds = [
    "cd monorepo/frontend",
    "npm ci"
]

[phases.build]
builder = "NIXPACKS"
cmds = [
    "cd monorepo/frontend",
    "npm run build:prod"
]

[start]
cmd = "cd monorepo/frontend && node dist/frontend/server/server.mjs"

[deploy]
region = "us-west2"
runtime = "V2"
numReplicas = 1
sleepApplication = false
multiRegionConfig = {"us-west2":{"numReplicas":1}}
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10