[build]
builder = "heroku/buildpacks:20"

[phases.setup]
nixPkgs = ['nodejs_20', 'nodePackages.npm']

[phases.install]
dependsOn = ['setup']
workingDirectory = "frontend"
cmds = ["npm install --verbose"]

[phases.build]
workingDirectory = "frontend"
cmds = ["npm run build:prod"]

[start]
workingDirectory = "frontend"
cmd = "npm start"
