[phases.setup]
nixPkgs = ["nodejs-18_x"]
dir = "monorepo/frontend"

[phases.install]
cmds = [
  "pwd", 
  "ls -la", 
  "npm install"
]

[phases.build]
cmds = ["npm run build:prod"]

[start]
cmd = "npm start"
