[build]
  base = "frontend"
  command = "npm i && npm run build:prod"
  publish = "dist/browser"

[build.environment]
  NODE_VERSION = "20.0.0"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.csr.html"
  status = 200