# Angular frontend configuration
[context.frontend]
  base = "frontend-skillio"
  command = "npm i && npm run build:prod"
  publish = "dist/frontend-skillio/browser"

  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Next.js landing page configuration
[context.landing-skillio]
  base = "landing-skillio"
  command = "npm i && npm run build" 
  publish = "out"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/landing-skillio/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/landing-skillio/out/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"