name: Deploy Frontend

on:
  push:
    branches:
      - test
      - main
    paths:
      - 'frontend/**'  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image for Frontend
        run: |
          docker build -t skillio-frontend -f frontend/Dockerfile .

      - name: Log in to Railway
        run: |
          railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy Frontend to Railway
        run: |
          railway up --service skillio-frontend --detached
