name: Deploy Frontend

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Nixpacks
        run: |
          curl -fsSL https://nixpacks.com/install.sh | sh

      - name: Build and Deploy
        run: |
          nixpacks build . --name skillio-frontend
