name: Frontend Build Validation

on:
  push:
    branches:
      - test
    paths:
      - 'monorepo/frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'monorepo/frontend/package-lock.json'

      - name: Install dependencies
        working-directory: monorepo/frontend
        run: npm ci

      - name: Build SSR
        working-directory: monorepo/frontend
        run: npm run build:ssr