name: Deploy Frontend

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Instala Nixpacks usando npm
      - name: Install Nixpacks
        run: npm install -g @railway/nixpacks

      - name: Build and Deploy
        run: |
          nixpacks build . --name skillio-frontend
